---
title: "week12"
author: "Richard"
date: "2026-04-20"
output: html_document
---

# Script Settings and Resources

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RedditExtractoR)
library(tm)
library(textclean)
library(textstem)
library(NLP)
library(stm)
library(wordcloud)
library(caret)

```

# Data Import and Cleaning

```{r}
# urls <- find_thread_urls(subreddit = "iopsychology", period="year", sort_by="new")
# 
# content <- get_thread_content(urls[1,"url"])
# dataset <- content$threads
# 
# download_tbl <- tibble()
# for (i in 1:35) {   # nrow(urls)) {
#   message(i)
#   content <- get_thread_content(urls[i,"url"])
#   dataset <- content$threads
#   download_tbl <- bind_rows(download_tbl, dataset)
#   Sys.sleep(7)
# }
# 
# week12_tbl <- download_tbl %>%
#   select(title, upvotes)
# 
# saveRDS(week12_tbl, "../out/week12.RDS")
week12_tbl <- readRDS("../out/week12.RDS")
```

# Analysis 

```{r}
corpus <- VCorpus(VectorSource(week12_tbl$title))

# Preprocessing using tm
corpus_prep <- corpus %>%
  tm_map(content_transformer(function(x) str_remove_all(x, "(?<=\\b[A-Z])\\.(?=[A-Z]\\b)"))) %>%
  tm_map(content_transformer(replace_contraction)) %>%
  tm_map(content_transformer(str_to_lower)) %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(lemmatize_words) %>%
  tm_map(removeWords, c("io", "iopsych", "io psychology", "i-o psychology", "iopsych", "iopsychology", stopwords("en"))) %>%
  tm_map(stripWhitespace)

compare_them <- function(c1, c2) {
  i <- sample(1:nrow(week12_tbl), size = 1)
  # message(week12_tbl[i,"title"])
  message(c1[[i]]$content)
  message(c2[[i]]$content)
}

# io_dtm <- DocumentTermMatrix(corpus_prep)
myTokenizer <- function(x) {
  unlist(lapply(ngrams(words(x), 1:2), paste, collapse = " "))
}

io_dtm <- DocumentTermMatrix(
  corpus_prep, 
  control = list(tokenize = myTokenizer))

io_slim_dtm <- removeSparseTerms(io_dtm, .95)

nrow(week12_tbl) / length(io_slim_dtm$dimnames$Terms)

dfm2stm <- readCorpus(io_slim_dtm, type="slam")
kresult <- searchK(
  dfm2stm$documents,
  dfm2stm$vocab,
  K = seq(2, 4, by = 1)
)
plot(kresult)
labelTopics(topic_model, n=2)
findThoughts(topic_model, texts=blogs$documents, n=3)
plot(topic_model, type="summary", n=2)
topicCorr(topic_model)
plot(topicCorr(topic_model))

kept_indices <- as.integer(names(dfm2stm$documents))
all_indices <- 1:nrow(io_slim_dtm)
dropped_indices <- setdiff(all_indices, kept_indices)

week12_mod_tbl <- mutate(week12_tbl, rn = row_number())
week12_kept_tbl <- week12_mod_tbl[kept_indices, ]

topic_labels <- tibble(
  topic = c(1, 2, 3),
  topic_label = c("teaching", "jobs", "other")
)

topics_tbl <- tibble(
  doc_id = week12_kept_tbl$rn,
  original = week12_kept_tbl$title,
  topic = apply(topic_model$theta, 1, which.max),
  # topic_label = ,
  probability = apply(topic_model$theta, 1, max),
  upvotes = week12_kept_tbl$upvotes
) %>%
  left_join(topic_labels)

io_slim_tbl <- io_slim_dtm %>% as.matrix %>% as_tibble
io_slim_kept_tbl <- io_slim_tbl[kept_indices, ]

ml_tbl <- io_slim_kept_tbl %>%
  cbind(upvotes = topics_tbl$upvotes) %>%
  cbind(topic = topics_tbl$topic) %>%
  mutate(topic = as.factor(topic))

holdout_indices <- createDataPartition(ml_tbl$upvotes, 
                                       p = .25, 
                                       list=F)
io_holdout <- ml_tbl[holdout_indices,]
io_training <- ml_tbl[-holdout_indices,]

model1 <- train(
  upvotes ~ .,
  select(io_training, -topic),
  method = "glmnet",
  na.action = na.pass,
  preProcess=c("medianImpute","center","nzv","scale"),
  trControl=trainControl(
    method="cv", number=10, verboseIter=T
  )
)

model2 <- train(
  upvotes ~ .,
  io_training,
  method = "glmnet",
  na.action = na.pass,
  preProcess=c("medianImpute","center","nzv","scale"),
  trControl=trainControl(
    method="cv", number=10, verboseIter=T
  )
)

summary(resamples(list("notopic"=model1, "full"=model2)))
dotplot(resamples(list("notopic"=model1, "full"=model2)))

cor(predict(model1, io_holdout$upvotes), io_holdout$upvotes)
cor(predict(model2, io_holdout$upvotes), io_holdout$upvotes)

```

# Visualization

```{r}
io_tbl <- io_dtm %>% as.matrix %>% as_tibble
wordCounts <- colSums(io_slim_tbl)
wordNames <- names(io_slim_tbl)
wordcloud::wordcloud(wordNames, wordCounts, max.words = 50)
```
